name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  checkout:
    name: "Checkout Ansible playbooks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'dreikanter/feeder-ansible'
          ref: 'master'
          path: 'feeder-ansible'
