name: Deploy
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  checkout:
    name: "Checkout Ansible playbooks"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
        with:
          repository: "dreikanter/feeder-ansible"
          ref: "master"
          path: "feeder-ansible"
  deploy:
    name: "Execute deployment playbook"
    needs: "checkout"
    runs-on: "ubuntu-latest"
    container:
      image: "debian:buster-slim"
      volumes:
        - "feeder-ansible:/feeder-ansible"
    steps:
      - run: "uname"
      - run: "whoami"
      - run: "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main"
      - run: "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367"
      - run: "sudo apt update"
      - run: "sudo apt install ansible"
      - run: "ansible --version"
