name: Deploy
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  checkout:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
        with:
          repository: "dreikanter/feeder-ansible"
          ref: "chore/github_action"
          path: "feeder-ansible"
      - name: "Install Ansible"
        run: |
          sudo apt-get update
          sudo apt install software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible
      - name: "Create SSH key"
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          ssh-keyscan -H "$SSH_TARGET_HOST" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_TARGET_HOST: ${{secrets.SSH_TARGET_HOST}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
